// Generated from DYO_TeknikO_Uygulama_Renk_Katalogu_v1.json. Do not edit source identities by hand.
// previewHex is a secondary digital preview, NOT an official DYO HEX specification.
export interface DyoColor {
  brand:"DYO";colorCode:string;colorName:string|null;previewHex:string;
  collections:readonly string[];usageAreas:readonly string[];
}
export const DYO_SOURCE_SHA256="94ba2c53646074e167786fc73df307d0f1c77c0e4b88f7eb7fba3fbf3f3761b0";
export const DYO_SOURCE_RECORD_COUNT=208;
export const DYO_METADATA_READY_COUNT=208;
export const DYO_METADATA_PENDING_COUNT=286;
export const DYO_MISSING_PREVIEW_COUNT=0;
export const DYO_PREVIEW_WARNING="Ekrandaki renkler önizleme amaçlıdır. Nihai renk seçimi DYO renk koduna göre yapılır.";
export const DYO_READY_COLORS:readonly DyoColor[]=[
  {"brand":"DYO","colorCode":"0141","colorName":"MELTEM","previewHex":"#EEE6DE","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0142","colorName":"KARTEPE","previewHex":"#FAFBEB","collections":["2025 Renk Kartelası","Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"0202","colorName":"ILIK MAYA","previewHex":"#D0C8BC","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"0306","colorName":"ŞAMPANYA","previewHex":"#F4DBBF","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0355","colorName":"BELCE BEJİ","previewHex":"#E8DFC8","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0374","colorName":"MİSKET","previewHex":"#DEE4D7","collections":["Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"0390","colorName":null,"previewHex":"#E9F3DE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0447","colorName":"SALDA KUMU","previewHex":"#E9EAE0","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"0472","colorName":"YENİ GÜLKURUSU","previewHex":"#D6A0A6","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0542","colorName":"ROZET GÜMÜŞÜ","previewHex":"#B4B4B5","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"0564","colorName":null,"previewHex":"#F4F7ED","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0567","colorName":"YENİ YAKAMOZ","previewHex":"#F4EFED","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0570","colorName":null,"previewHex":"#E7D7E1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0588","colorName":null,"previewHex":"#DCDDE1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0606","colorName":null,"previewHex":"#D5DFDB","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0655","colorName":null,"previewHex":"#BEB2AA","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0662","colorName":null,"previewHex":"#EACFB0","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0666","colorName":"YENİ BELİZ","previewHex":"#DEDFE0","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0667","colorName":null,"previewHex":"#BEABA0","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0683","colorName":null,"previewHex":"#A79576","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0700","colorName":null,"previewHex":"#C7B29B","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0707","colorName":null,"previewHex":"#C8C0A3","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0716","colorName":null,"previewHex":"#E1D9C7","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0720","colorName":null,"previewHex":"#EADBB2","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0721","colorName":"TROPİK","previewHex":"#FBFAE4","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0723","colorName":"TAŞ SANDIK","previewHex":"#DDD7CC","collections":["Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"0729","colorName":null,"previewHex":"#C9C7C0","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0735","colorName":null,"previewHex":"#B2AFA6","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0740","colorName":null,"previewHex":"#C7C3B8","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0748","colorName":null,"previewHex":"#8C9288","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0755","colorName":null,"previewHex":"#ACB1A8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0779","colorName":null,"previewHex":"#CAD0CB","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0807","colorName":null,"previewHex":"#E6DCC8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0833","colorName":null,"previewHex":"#E3B43C","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0901","colorName":null,"previewHex":"#E2CC48","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0932","colorName":null,"previewHex":"#FAC89D","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"0986","colorName":"BEGONYA","previewHex":"#FFE1B7","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"1071","colorName":"TÜLDEN","previewHex":"#EEECE7","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"1225","colorName":"İNCEKUM","previewHex":"#D6CDB4","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"1621","colorName":"KAYMAK TAŞI","previewHex":"#D0CCA4","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"1906","colorName":"SERİN LİLA","previewHex":"#D2D5E6","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"1917","colorName":"LEYLAK","previewHex":"#DDB3C9","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"1987","colorName":"KÖPÜK","previewHex":"#ECE5C8","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2090","colorName":"GÜZ","previewHex":"#F2E8A9","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2251","colorName":"KUMSAL","previewHex":"#FAF2DD","collections":["2025 Renk Kartelası","Sentetik Grubu","İç Cephe Renklerimiz"],"usageAreas":["Ahşap/Metal - Sentetik","İç Cephe"]},
  {"brand":"DYO","colorCode":"2412","colorName":null,"previewHex":"#FDE9CF","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2626","colorName":"SINAV SARISI","previewHex":"#F6DF45","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2633","colorName":null,"previewHex":"#FEEC7A","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2640","colorName":null,"previewHex":"#E5946C","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2641","colorName":null,"previewHex":"#F6EBA0","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2644","colorName":null,"previewHex":"#F1E6B5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2647","colorName":null,"previewHex":"#D47144","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2651","colorName":null,"previewHex":"#F3B373","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2653","colorName":null,"previewHex":"#CB9E25","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2660","colorName":null,"previewHex":"#E3C964","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2662","colorName":null,"previewHex":"#CAA382","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2665","colorName":null,"previewHex":"#E3B58B","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2667","colorName":null,"previewHex":"#E6D876","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2670","colorName":null,"previewHex":"#A4853B","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2672","colorName":null,"previewHex":"#C1C66A","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2675","colorName":null,"previewHex":"#746C4F","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2678","colorName":null,"previewHex":"#FAF1B4","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2684","colorName":null,"previewHex":"#C09839","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2687","colorName":null,"previewHex":"#ABA07A","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2689","colorName":null,"previewHex":"#E0EBAA","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2691","colorName":null,"previewHex":"#FED7C3","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2694","colorName":null,"previewHex":"#CABF8B","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2697","colorName":null,"previewHex":"#FAC2AC","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2832","colorName":null,"previewHex":"#E4C834","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"2914","colorName":"YENİ FİLDİŞİ","previewHex":"#F9F1CD","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3037","colorName":null,"previewHex":"#AAB978","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3038","colorName":null,"previewHex":"#93A455","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3077","colorName":null,"previewHex":"#8B9366","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3135","colorName":null,"previewHex":"#B0C2A0","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3152","colorName":"NİL YEŞİLİ","previewHex":"#E3F1E6","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3212","colorName":"IRMAK YEŞİLİ","previewHex":"#97B1A7","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3225","colorName":"TOMURCUK","previewHex":"#D0E074","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3310","colorName":"LUNA OTU","previewHex":"#808A87","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"3313","colorName":"FISTIKİ","previewHex":"#C5D775","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3347","colorName":null,"previewHex":"#B6B775","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3352","colorName":null,"previewHex":"#698378","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"3898","colorName":null,"previewHex":"#8FA081","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4114","colorName":"YENİ ROMANTİK","previewHex":"#F9EFE9","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4217","colorName":"YENİ SOMON","previewHex":"#F6B88F","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4348","colorName":"YALIN","previewHex":"#E4D7E3","collections":["Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"4366","colorName":null,"previewHex":"#D4AC9C","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4379","colorName":null,"previewHex":"#C07D95","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4389","colorName":null,"previewHex":"#A88A8E","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4435","colorName":null,"previewHex":"#F8A07C","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4474","colorName":"HAYAL PEMBESİ","previewHex":"#F3E7E5","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4547","colorName":"ŞARABİ","previewHex":"#832F2F","collections":["Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"4568","colorName":"ŞİRİN PEMBE","previewHex":"#F6DCE0","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4681","colorName":null,"previewHex":"#FFE6D8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4685","colorName":"SALTANAT KIRMIZI","previewHex":"#C03026","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4689","colorName":null,"previewHex":"#F4EBEE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4698","colorName":null,"previewHex":"#E4B1C1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4699","colorName":null,"previewHex":"#EACABB","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4701","colorName":null,"previewHex":"#CAB4C2","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4703","colorName":null,"previewHex":"#D6A8C7","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4705","colorName":null,"previewHex":"#E9BEC1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4707","colorName":"EFSANE","previewHex":"#906B91","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"4708","colorName":null,"previewHex":"#79454C","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"4709","colorName":null,"previewHex":"#EDE1ED","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4710","colorName":null,"previewHex":"#F7E7EB","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4712","colorName":null,"previewHex":"#CDB2AC","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4713","colorName":null,"previewHex":"#F6D6E8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4714","colorName":"HİNT PEMBESİ","previewHex":"#D8C9CA","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4715","colorName":null,"previewHex":"#BBA5B8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4717","colorName":"LİLYUM PEMBE","previewHex":"#DC83B2","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4722","colorName":null,"previewHex":"#E0D2E3","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4726","colorName":null,"previewHex":"#CA9165","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4738","colorName":null,"previewHex":"#BBA8D5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4740","colorName":null,"previewHex":"#965547","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4744","colorName":null,"previewHex":"#D1C3D8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4745","colorName":null,"previewHex":"#E1D5DB","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4748","colorName":null,"previewHex":"#A797B2","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4750","colorName":null,"previewHex":"#B06656","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4752","colorName":null,"previewHex":"#E1D2E3","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4753","colorName":null,"previewHex":"#E98D89","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4755","colorName":null,"previewHex":"#E3A698","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4756","colorName":null,"previewHex":"#844D3B","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4758","colorName":null,"previewHex":"#9E2B27","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4759","colorName":null,"previewHex":"#F0CEC5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4760","colorName":null,"previewHex":"#FEECE3","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4761","colorName":null,"previewHex":"#B66481","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"4907","colorName":"PRENSES PEMBE","previewHex":"#ED8996","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5046","colorName":"MİNE","previewHex":"#E0E8E7","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5160","colorName":"HERCAİ","previewHex":"#806B7F","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5161","colorName":null,"previewHex":"#927D54","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5174","colorName":"YENİ KESEKAĞIDI","previewHex":"#D4BF96","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5177","colorName":"ASİL LİLA","previewHex":"#DBBECE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5213","colorName":null,"previewHex":"#D7C7B5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5355","colorName":"TOHUM","previewHex":"#C2B18A","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5579","colorName":"VİZON","previewHex":"#74685F","collections":["Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"5664","colorName":"ROMANTİK","previewHex":"#F5F0EC","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5673","colorName":"YAKAMOZ","previewHex":"#EBE6EA","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"5909","colorName":"LATTE","previewHex":"#9E7E72","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6110","colorName":null,"previewHex":"#B0CBC2","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6119","colorName":null,"previewHex":"#91AE9F","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6122","colorName":null,"previewHex":"#7E8E86","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6181","colorName":null,"previewHex":"#E6E8EE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6212","colorName":"BUZ MAVİSİ","previewHex":"#CCDCDE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6225","colorName":null,"previewHex":"#585E77","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6253","colorName":null,"previewHex":"#D4E1E1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6254","colorName":null,"previewHex":"#867A9F","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6256","colorName":null,"previewHex":"#77B6B2","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6260","colorName":null,"previewHex":"#527B7A","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6263","colorName":null,"previewHex":"#CFE5F4","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6265","colorName":"NAZARLIK","previewHex":"#C6D7E3","collections":["Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"6267","colorName":null,"previewHex":"#656B80","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6269","colorName":"DENİZ ATI","previewHex":"#DAE5E4","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6270","colorName":null,"previewHex":"#9BC6DD","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6272","colorName":null,"previewHex":"#9A9AAE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6273","colorName":null,"previewHex":"#808F96","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6276","colorName":null,"previewHex":"#CADCE5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6278","colorName":null,"previewHex":"#BBC5CE","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6280","colorName":"TOZ MAVİ","previewHex":"#96A1AA","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6282","colorName":null,"previewHex":"#6F7691","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6286","colorName":null,"previewHex":"#AABFD6","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6363","colorName":"ADRİYATİK","previewHex":"#3C637F","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"6591","colorName":"ÇİSENTİ","previewHex":"#E8F0EA","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6627","colorName":"GÖKÇE","previewHex":"#A7BDD3","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6656","colorName":null,"previewHex":"#CCD8DB","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6666","colorName":null,"previewHex":"#3C84AA","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6686","colorName":"ARYA","previewHex":"#E1D2E4","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"6706","colorName":null,"previewHex":"#D9EAF3","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6709","colorName":null,"previewHex":"#E3E7ED","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6716","colorName":null,"previewHex":"#BCCED1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6721","colorName":null,"previewHex":"#363E4B","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6767","colorName":"AKVARYUM","previewHex":"#256F8F","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6853","colorName":null,"previewHex":"#446987","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"6946","colorName":null,"previewHex":"#ABC1CF","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7127","colorName":"BUZ BEYAZI","previewHex":"#E2E5CD","collections":["Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7169","colorName":null,"previewHex":"#9C9793","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7194","colorName":"TOZ DUMAN","previewHex":"#BDB8AE","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7202","colorName":"ZEYTUNİ","previewHex":"#828171","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"7233","colorName":"PAMPAS OTU","previewHex":"#CBC5C3","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7252","colorName":"ALAÇATI","previewHex":"#E2DECC","collections":["2025 Renk Kartelası","Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7281","colorName":null,"previewHex":"#B5B5B5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7344","colorName":null,"previewHex":"#D6D4D6","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7348","colorName":null,"previewHex":"#B6B6B8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7548","colorName":null,"previewHex":"#E2E0DC","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7550","colorName":"YENİ ÇAĞIL","previewHex":"#EBEDE6","collections":["2025 Renk Kartelası","Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7557","colorName":null,"previewHex":"#9C9699","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7558","colorName":"BELİZ","previewHex":"#E1E2E1","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7565","colorName":"BUZ GÜMÜŞÜ","previewHex":"#E1E0DE","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7567","colorName":null,"previewHex":"#868990","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7568","colorName":null,"previewHex":"#7C858A","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7569","colorName":null,"previewHex":"#BEC8CD","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7570","colorName":"GÖLGEM","previewHex":"#A4A4A8","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7571","colorName":"SADE GRİ","previewHex":"#DEDFE0","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7573","colorName":null,"previewHex":"#A8B0B4","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7683","colorName":null,"previewHex":"#B6B5B5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7691","colorName":"HARELİ","previewHex":"#DBCFC9","collections":["2025 Renk Kartelası","Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7702","colorName":null,"previewHex":"#CEC8BA","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7730","colorName":"DERETAŞI","previewHex":"#9C9390","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"7873","colorName":null,"previewHex":"#AEA692","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"7962","colorName":"ALÜVYON","previewHex":"#B6B098","collections":["2025 Renk Kartelası","Dış Cephe Renklerimiz","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"7963","colorName":"KEMİK BEYAZI","previewHex":"#EEECE2","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"8024","colorName":"IHLAMUR","previewHex":"#FCF5E5","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"8549","colorName":null,"previewHex":"#645D60","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"8559","colorName":null,"previewHex":"#BCA9AF","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"8565","colorName":null,"previewHex":"#7B5F6D","collections":["İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"8585","colorName":"BADEM","previewHex":"#A4624B","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"9062","colorName":"YOSUN YEŞİLİ","previewHex":"#CFDEC4","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
  {"brand":"DYO","colorCode":"9064","colorName":"DEMİRDAĞI","previewHex":"#818287","collections":["2025 Renk Kartelası","Hobi Boyaları","İç Cephe Renklerimiz"],"usageAreas":["Hobi","İç Cephe"]},
  {"brand":"DYO","colorCode":"9072","colorName":null,"previewHex":"#7D7567","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["Dış Cephe","İç Cephe"]},
  {"brand":"DYO","colorCode":"9084","colorName":null,"previewHex":"#AAB7A7","collections":["2025 Renk Kartelası","İç Cephe Renklerimiz"],"usageAreas":["İç Cephe"]},
];
export const isDyoInteriorColor=(color:Pick<DyoColor,"usageAreas">)=>color.usageAreas.includes("İç Cephe");
export const DYO_WALL_COLORS:readonly DyoColor[]=DYO_READY_COLORS.filter(isDyoInteriorColor);
export const findDyoWallColor=(code:string):DyoColor|undefined=>DYO_WALL_COLORS.find(color=>color.colorCode===code);
const searchText=(value:string)=>value.toLocaleLowerCase("tr-TR").normalize("NFD")
  .replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i");
export const searchDyoWallColors=(query:string):readonly DyoColor[]=>{
  const needle=searchText(query.trim());
  return needle?DYO_WALL_COLORS.filter(color=>searchText(`${color.colorCode} ${color.colorName??""}`).includes(needle)):DYO_WALL_COLORS;
};
