'use client';
import {beginUiAction,endUiAction} from '@/lib/use-ui-action';
import {useState} from 'react';import {useRouter} from 'next/navigation';
export function Stage10OperationIntervention({requestId,currentJobId,closed}:{requestId:string;currentJobId:string|null;closed:boolean}){const router=useRouter();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function submit(form:FormData){
if(!beginUiAction(setBusy))return;
try {
setBusy(true);const action=String(form.get('action'));const body={action,reason:String(form.get('reason')),technicianId:String(form.get('technicianId')||''),expectedJobId:currentJobId,idempotencyKey:crypto.randomUUID()};const response=await fetch(`/api/admin/stage10/requests/${requestId}/intervention`,{signal:AbortSignal.timeout(30000),method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));setBusy(false);setMessage(response.ok?'Operasyon müdahalesi kaydedildi.':data.error??'İşlem tamamlanamadı.');if(response.ok)router.refresh();
}catch {setMessage('Bağlantı kurulamadı. İşlem durumunu kontrol edip yeniden deneyin.');}
finally {endUiAction(setBusy);setBusy(false);}
}if(closed)return <p className="text-sm text-slate-600">Kesin kapanmış hizmete müdahale edilemez.</p>;return <form action={submit} className="grid gap-2"><select name="action" className="rounded-xl border border-slate-300 p-2"><option value="change_technician">Usta değiştir</option><option value="cancel">Hizmeti iptal et</option></select><input name="technicianId" placeholder="Yeni usta kullanıcı ID (iptalde boş)" className="rounded-xl border border-slate-300 p-2"/><textarea name="reason" required minLength={10} maxLength={1000} placeholder="Müdahale gerekçesi" className="rounded-xl border border-slate-300 p-2"/><button aria-busy={busy} disabled={busy} className="rounded-xl bg-[#B95236] px-4 py-2 text-sm font-bold text-white">{busy?'İşleniyor…':'Uygula'}</button>{message&&<p role="status" className="text-sm">{message}</p>}</form>}
