'use client';
import {beginUiAction,endUiAction} from '@/lib/use-ui-action';
import {useState} from 'react';import {useRouter} from 'next/navigation';
function useSubmit(){const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');return {busy,message,async send(url:string,body:Record<string,unknown>){
if(!beginUiAction(setBusy))return;
try {
setBusy(true);setMessage('');const r=await fetch(url,{signal:AbortSignal.timeout(30000),method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));setBusy(false);setMessage(r.ok?'İşlem kaydedildi.':data.error??'İşlem tamamlanamadı.');if(r.ok)router.refresh();
}catch {setMessage('Bağlantı kurulamadı. İşlem durumunu kontrol edip yeniden deneyin.');}
finally {endUiAction(setBusy);setBusy(false);}
}}}
export function AdditionalCostAdminAction({id,status,version}:{id:string;status:string;version:number}){const s=useSubmit();return <form action={form=>s.send(`/api/admin/stage10/additional-costs/${id}`,{action:String(form.get('action')),reason:String(form.get('reason')),version})} className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><input name="reason" required minLength={10} maxLength={1000} placeholder="Gerekçe" className="rounded-xl border border-slate-300 p-2"/><select name="action" className="rounded-xl border border-slate-300 p-2">{status==='pending_admin'?<><option value="approve">Yönetici onayı</option><option value="reject">Yönetici reddi</option></>:<><option value="continue">Önceki kapsamla devam</option><option value="cancel">Hizmeti iptal et</option></>}</select><button aria-busy={s.busy} disabled={s.busy} className="rounded-xl bg-[#B95236] px-4 py-2 text-sm font-bold text-white sm:col-span-2">{s.busy?'İşleniyor…':'Kararı kaydet'}</button>{s.message&&<p role="status" className="text-sm sm:col-span-2">{s.message}</p>}</form>}
export function ComplaintAdminAction({id,version}:{id:string;version:number}){const s=useSubmit();return <form action={form=>s.send(`/api/admin/stage10/complaints/${id}`,{action:'decide',finalCategory:String(form.get('finalCategory')),decision:String(form.get('decision')),reason:String(form.get('reason')),subjectUserId:String(form.get('subjectUserId')||''),sanctionEndsAt:String(form.get('sanctionEndsAt')||''),version})} className="mt-3 grid gap-2"><input name="finalCategory" required minLength={2} maxLength={100} placeholder="Nihai kategori" className="rounded-xl border border-slate-300 p-2"/><select name="decision" className="rounded-xl border border-slate-300 p-2"><option value="no_action">İşlem yok</option><option value="warning">Uyarı</option><option value="restrict_new_operations">Yeni işlemleri kısıtla</option><option value="temporary_suspension">Geçici askıya al</option><option value="permanent_closure">Kalıcı hesap kapatma</option><option value="finance_review">Finansal/iade incelemesi</option></select><input name="subjectUserId" placeholder="Yaptırım uygulanacak kullanıcı ID (işlem yoksa boş)" className="rounded-xl border border-slate-300 p-2"/><input name="sanctionEndsAt" type="datetime-local" className="rounded-xl border border-slate-300 p-2"/><textarea name="reason" required minLength={20} maxLength={2000} placeholder="Gerekçeli nihai karar" className="rounded-xl border border-slate-300 p-2"/><button aria-busy={s.busy} disabled={s.busy} className="rounded-xl bg-[#B95236] px-4 py-2 text-sm font-bold text-white">{s.busy?'İşleniyor…':'Sonuçlandır'}</button>{s.message&&<p role="status" className="text-sm">{s.message}</p>}</form>}
export function ComplaintInfoRequest({id}:{id:string}){const s=useSubmit();return <form action={form=>s.send(`/api/admin/stage10/complaints/${id}`,{action:'request_info',message:String(form.get('message'))})} className="mt-3 flex flex-wrap gap-2"><input name="message" required minLength={10} maxLength={1000} placeholder="Ek bilgi talebi" className="min-w-64 flex-1 rounded-xl border border-slate-300 p-2"/><button aria-busy={s.busy} disabled={s.busy} className="rounded-xl border border-[#B95236] bg-white px-4 py-2 text-sm font-bold text-[#A8422B]">{s.busy?'İşleniyor…':'Bilgi iste'}</button>{s.message&&<p role="status" className="w-full text-sm">{s.message}</p>}</form>}
export function ComplaintDecisionCorrection({id}:{id:string}){const s=useSubmit();return <form action={form=>s.send(`/api/admin/stage10/complaints/${id}`,{action:'correct',correctionText:String(form.get('correctionText')),revokeSanction:form.get('revokeSanction')==='on'})} className="mt-3 grid gap-2"><textarea name="correctionText" required minLength={20} maxLength={2000} placeholder="Değiştirilemez karara eklenecek düzeltme kaydı" className="rounded-xl border border-slate-300 p-2"/><label className="flex items-center gap-2 text-sm"><input name="revokeSanction" type="checkbox"/> Bağlı yaptırımı ayrı kayıtla sona erdir</label><button aria-busy={s.busy} disabled={s.busy} className="rounded-xl border border-[#B95236] bg-white px-4 py-2 text-sm font-bold text-[#A8422B]">{s.busy?'İşleniyor…':'Düzeltme kaydı ekle'}</button>{s.message&&<p role="status" className="text-sm">{s.message}</p>}</form>}
export function WarrantyAdminAction({id,version}:{id:string;version:number}){const s=useSubmit();return <form action={form=>s.send(`/api/admin/stage10/warranty/${id}`,{action:'decide',accept:String(form.get('decision'))==='accept',customerReason:String(form.get('customerReason')),internalReason:String(form.get('internalReason')),version})} className="mt-3 grid gap-2"><select name="decision" className="rounded-xl border border-slate-300 p-2"><option value="accept">Kabul</option><option value="reject">Ret</option></select><input name="customerReason" required minLength={10} maxLength={1000} placeholder="Müşteriye gösterilecek kısa gerekçe" className="rounded-xl border border-slate-300 p-2"/><textarea name="internalReason" required minLength={10} maxLength={2000} placeholder="İç değerlendirme" className="rounded-xl border border-slate-300 p-2"/><button aria-busy={s.busy} disabled={s.busy} className="rounded-xl bg-[#B95236] px-4 py-2 text-sm font-bold text-white">{s.busy?'İşleniyor…':'Kararı kaydet'}</button>{s.message&&<p role="status" className="text-sm">{s.message}</p>}</form>}
export function WarrantyAssignmentAction({id,version}:{id:string;version:number}){const s=useSubmit();return <form action={form=>s.send(`/api/admin/stage10/warranty/${id}`,{action:'assign',technicianId:String(form.get('technicianId')),version})} className="mt-3 flex flex-wrap gap-2"><input name="technicianId" required placeholder="Usta kullanıcı ID" className="min-w-64 flex-1 rounded-xl border border-slate-300 p-2"/><button aria-busy={s.busy} disabled={s.busy} className="rounded-xl bg-[#B95236] px-4 py-2 text-sm font-bold text-white">{s.busy?'İşleniyor…':'Düzeltme ata'}</button>{s.message&&<p role="status" className="w-full text-sm">{s.message}</p>}</form>}
