const labels:Record<string,string>={
 corrected:'Düzeltildi',admin_continue:'Önceki kapsamla devam',admin_cancelled:'Yönetici iptal etti',withdrawn:'Geri çekildi',rescheduled:'Yeniden planlandı',auto:'Otomatik atama',manual:'Yönetici ataması',
 distributing:'Usta aranıyor',admin_intervention:'Yönetici incelemesi bekleniyor',request_open:'Talep açık',
 pending:'Bekliyor',approved:'Onaylandı',rejected:'Reddedildi',verified:'Doğrulandı',expired:'Süresi doldu',draft:'Taslak',active:'Aktif',inactive:'Pasif',
 diagnosing:'Değerlendiriliyor',awaiting_quote:'Teklif bekleniyor',quoted:'Teklif sunuldu',quote_accepted:'Teklif kabul edildi',dispatching:'Usta aranıyor',assigned:'Usta atandı',in_progress:'Devam ediyor',completed:'Tamamlandı',cancelled:'İptal edildi',technician_unavailable:'Usta bulunamadı',
 pending_admin:'Yönetici incelemesinde',pending_customer:'Müşteri kararı bekleniyor',customer_accepted:'Müşteri kabul etti',customer_rejected:'Müşteri reddetti',admin_rejected:'Yönetici reddetti',continued_original:'Önceki kapsamla devam',service_cancelled:'Hizmet iptal edildi',
 under_review:'İnceleniyor',resolved:'Sonuçlandı',correction_pending:'Düzeltme bekleniyor',correction_assigned:'Düzeltme atandı',offered:'Teklif edildi',accepted:'Kabul edildi',declined:'Reddedildi',scheduled:'Planlandı',confirmed:'Onaylandı',no_show:'Katılım olmadı',broadcasting:'Dağıtılıyor',exhausted:'Dağıtım sonuçsuz',closed:'Kapandı',open:'Açık',
 automatic:'Otomatik atama',admin_manual:'Yönetici ataması',original_technician:'İlk usta',alternative_technician:'Alternatif usta',customer:'Müşteri',technician:'Usta',admin:'Yönetici',normal:'Normal',high:'Yüksek',critical:'Kritik',
 no_action:'İşlem yok',warning:'Uyarı',restrict_new_operations:'Yeni işlemler kısıtlı',temporary_suspension:'Geçici askıya alma',permanent_closure:'Hesap kapatma',finance_review:'Finansal inceleme',revoked:'Sona erdirildi',electronic_30:'30 gün garanti',non_electronic_7:'7 gün garanti'
};
export function statusLabel(value:unknown){return typeof value==='string'?(labels[value]??'Durum bilgisi bekleniyor'):'Belirtilmedi';}
export function moneyLabel(value:unknown,currency='TRY'){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('tr-TR',{style:'currency',currency}).format(n):'Belirtilmedi';}

export function eventLabel(value:string){const known:Record<string,string>={"admin.manual_assignment": "Yönetici usta atadı", "appointment.rescheduled": "Randevu yeniden planlandı", "dispatch.accepted": "Dağıtım teklifi kabul edildi", "dispatch.round_started": "Dağıtım turu başladı", "distribution.exhausted": "Dağıtım sonuçsuz kaldı", "distribution.redistributed": "Yeniden dağıtım başladı", "distribution.started": "Usta dağıtımı başladı", "job.assigned": "İş atandı", "job.cancelled": "İş iptal edildi", "technician.availability_changed": "Usta müsaitliği güncellendi", "additional_cost.created": "Ek maliyet talebi oluşturuldu", "additional_cost.admin_approved": "Ek maliyet yönetici tarafından onaylandı", "additional_cost.admin_rejected": "Ek maliyet yönetici tarafından reddedildi", "additional_cost.admin_cancelled": "Ek maliyet nedeniyle hizmet iptal edildi", "additional_cost.admin_continued": "Önceki kapsamla devam kararı verildi", "additional_cost.customer_accepted": "Müşteri ek maliyeti kabul etti", "additional_cost.customer_rejected": "Müşteri ek maliyeti reddetti", "complaint.created": "Şikâyet oluşturuldu", "complaint.decision_corrected": "Şikâyet kararına düzeltme eklendi", "complaint.resolved": "Şikâyet sonuçlandı", "warranty.created": "Garanti talebi oluşturuldu", "warranty.correction_assigned": "Garanti düzeltmesi atandı", "warranty.correction_completed": "Garanti düzeltmesi tamamlandı", "warranty.correction_accepted": "Garanti düzeltmesi kabul edildi", "warranty.correction_declined": "Garanti düzeltmesi reddedildi", "technician.category_approved": "Usta kategorisi onaylandı", "technician.category_rejected": "Usta kategorisi reddedildi",'request.created':'Talep oluşturuldu','quote.created':'Teklif oluşturuldu','quote.accepted':'Teklif kabul edildi','job.started':'İş başladı','job.completed':'İş tamamlandı','job.appointment_timeout':'Randevu oluşturma süresi doldu','request.technician_unavailable':'Usta bulunamadı; talep kapandı','distribution.manual_assignment_required':'Yönetici ataması gerekiyor','admin.service_cancelled':'Hizmet yönetici tarafından iptal edildi','admin.technician_changed':'Usta değiştirildi'};return known[value]??`Operasyon kaydı (${value})`;}
