'use client';
import {beginUiAction,endUiAction} from '@/lib/use-ui-action';
import {useState} from 'react';import {useRouter} from 'next/navigation';
export function TechnicianCaseForm({kind,items}:{kind:'complaint'|'additional_cost';items:Array<{id:string;label:string}>}){const router=useRouter();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function submit(form:FormData){
if(!beginUiAction(setBusy))return;
try {
setBusy(true);setMessage('');form.set('idempotencyKey',crypto.randomUUID());const url=kind==='complaint'?'/api/stage10/complaints':'/api/stage10/additional-costs';const response=await fetch(url,{signal:AbortSignal.timeout(30000),method:'POST',body:form});const body=await response.json().catch(()=>({}));setBusy(false);setMessage(response.ok?(kind==='complaint'?'Şikâyetiniz inceleniyor.':'Ek maliyet talebi yönetici incelemesine gönderildi.'):body.error??'İşlem tamamlanamadı.');if(response.ok)router.refresh();
}catch {setMessage('Bağlantı kurulamadı. İşlem durumunu kontrol edip yeniden deneyin.');}
finally {endUiAction(setBusy);setBusy(false);}
}return <form action={submit} className="grid gap-4"><label className="text-sm font-semibold">{kind==='complaint'?'Hizmet talebi':'Aktif iş'}<select name={kind==='complaint'?'requestId':'jobId'} required className="mt-1 block w-full rounded-xl border border-slate-300 bg-white p-3"><option value="">Seçin</option>{items.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{kind==='additional_cost'&&<label className="text-sm font-semibold">Talep edilen fark (TL)<input name="amount" type="number" min="0.01" step="0.01" required className="mt-1 block w-full rounded-xl border border-slate-300 p-3"/></label>}<label className="text-sm font-semibold">{kind==='complaint'?'Açıklama':'Gerekçe'}<textarea name={kind==='complaint'?'description':'reason'} minLength={20} maxLength={1000} required className="mt-1 block min-h-28 w-full rounded-xl border border-slate-300 p-3"/></label><label className="text-sm font-semibold">Kanıt (isteğe bağlı)<input name="evidence" type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,video/webm,application/pdf" className="mt-1 block w-full rounded-xl border border-slate-300 p-3"/></label><button aria-busy={busy} disabled={busy||!items.length} className="rounded-xl bg-[#B95236] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'Gönderiliyor…':'Gönder'}</button>{message&&<p role="status" className="text-sm font-semibold">{message}</p>}</form>}
export function WarrantyCorrectionAction({id,status}:{id:string;status:string}){const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function act(action:string){
if(!beginUiAction(setBusy))return;
try {
setBusy(true);const r=await fetch(`/api/stage10/warranty-corrections/${id}`,{signal:AbortSignal.timeout(30000),method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});setBusy(false);if(r.ok){setMessage('İşlem kaydedildi.');router.refresh();}else{const body=await r.json().catch(()=>({}));setMessage(body.error??'İşlem tamamlanamadı.');}
}catch {setMessage('Bağlantı kurulamadı. İşlem durumunu kontrol edip yeniden deneyin.');}
finally {endUiAction(setBusy);setBusy(false);}
}return <div className="mt-2 flex flex-wrap gap-2">{status==='offered'&&<><button disabled={busy} aria-busy={busy} onClick={()=>act('accept')} className="to-primary">{busy?'İşleniyor…':'Kabul et'}</button><button disabled={busy} onClick={()=>act('decline')} className="rounded-xl border border-red-300 px-3 py-2 text-sm font-bold text-red-700">Reddet</button></>}{status==='accepted'&&<button disabled={busy} aria-busy={busy} onClick={()=>act('complete')} className="to-primary">{busy?'İşleniyor…':'Düzeltmeyi tamamla'}</button>}{message&&<p role="status" className="to-feedback w-full">{message}</p>}</div>}
