// Generated from BOYA_Son Hali.xlsx; do not edit prices by hand.
// Source SHA-256: d1e608505bd2b987d3ba29b40cfd7956284e3682d253746f033ed9cba241f288
export type PaintingSurface = "old_painted" | "new_plaster" | "satin_plaster_drywall" |
  "old_painted_ceiling" | "new_plaster_ceiling" | "satin_plaster_ceiling";
export type PaintingType = "white_lime" | "silicone_matte" | "plastic_matte" |
  "silicone_silk_matte" | "silicone_semi_matte" | "antibacterial_silicone_matte" |
  "antibacterial_silicone_silk_matte" | "antibacterial_plastic_matte" |
  "synthetic_gloss" | "synthetic_matte" | "silicone_soft_matte" | "ceiling_water_based";
export interface PaintingPoz {
  id:string; summaryRow:number; nameCell:string; priceCell:string; description:string;
  surface:PaintingSurface; paintType:PaintingType; coats:number; widePuttyInputIncluded:boolean;
  materialCostM2:number; laborCostM2:number; primerMaterialCostM2:number; priceM2:number;
}
export const PAINTING_SOURCE_SHA256="d1e608505bd2b987d3ba29b40cfd7956284e3682d253746f033ed9cba241f288";
export const MARKET_COST_FACTOR=1.2;
export const EXTRA_PUTTY_PRICE_M2=66.864;
export const PAINTING_POSITIONS:readonly PaintingPoz[]=[
  {id:"B2_F10",summaryRow:5,nameCell:"B2",priceCell:"F10",description:"Eski boyalı yüzeylere üç kat beyaz kireç badana yapılması (iç cephe)",surface:"old_painted",paintType:"white_lime",coats:3,widePuttyInputIncluded:false,materialCostM2:1.4125,laborCostM2:82.5,primerMaterialCostM2:0.0,priceM2:100.695},
  {id:"B13_F23",summaryRow:6,nameCell:"B13",priceCell:"F23",description:"Eski boyalı yüzeylere astar uygulanarak iki kat su bazlı silikonlu mat iç cephe",surface:"old_painted",paintType:"silicone_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:27.4815,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:107.9778},
  {id:"B26_F36",summaryRow:7,nameCell:"B26",priceCell:"F36",description:"Eski boyalı yüzeylere astar uygulanarak iki kat Su bazlı Plastik Mat İç Cephe Boyası",surface:"old_painted",paintType:"plastic_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:26.6715,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:107.0058},
  {id:"B39_F49",summaryRow:8,nameCell:"B39",priceCell:"F49",description:"Eski boyalı yüzeylere astar uygulanarak iki kat Su bazlı Silikonlu  İpek Mat İç Cephe Boyası",surface:"old_painted",paintType:"silicone_silk_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:30.4815,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:111.5778},
  {id:"B52_F62",summaryRow:9,nameCell:"B52",priceCell:"F62",description:"Eski boyalı yüzeylere astar uygulanarak iki kat Su bazlı  Silikonlu Yarı Mat İç Cephe Boyası",surface:"old_painted",paintType:"silicone_semi_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:34.3215,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:116.1858},
  {id:"B65_F76",summaryRow:10,nameCell:"B65",priceCell:"F76",description:"Eski boyalı yüzeylere astar uygulanarak iki kat Su bazlı Silikonlu Mat Antibakteriyel İç Cephe Boyası",surface:"old_painted",paintType:"antibacterial_silicone_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:37.0665,laborCostM2:67.5,primerMaterialCostM2:5.46,priceM2:125.4798},
  {id:"B79_F90",summaryRow:11,nameCell:"B79",priceCell:"F90",description:"Eski boyalı yüzeylere astar uygulanarak iki kat Su bazlı Silikonlu İpek Mat Antibakteriyel İç Cephe Boyası",surface:"old_painted",paintType:"antibacterial_silicone_silk_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:39.7515,laborCostM2:67.5,primerMaterialCostM2:5.46,priceM2:128.7018},
  {id:"B93_F104",summaryRow:12,nameCell:"B93",priceCell:"F104",description:"Eski boyalı yüzeylere astar uygulanarak iki kat Su bazlı Plastik Antibakteriyel İç Cephe Boyası",surface:"old_painted",paintType:"antibacterial_plastic_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:33.7275,laborCostM2:82.5,primerMaterialCostM2:5.46,priceM2:139.473},
  {id:"B107_F117",summaryRow:13,nameCell:"B107",priceCell:"F117",description:"Eski boyalı yüzeylere macun ve astar uygulanarak iki kat sentetik esaslı parlak boya yapılması (iç cephe)",surface:"old_painted",paintType:"synthetic_gloss",coats:2,widePuttyInputIncluded:false,materialCostM2:41.5315,laborCostM2:82.5,primerMaterialCostM2:10.08,priceM2:148.8378},
  {id:"B120_F130",summaryRow:14,nameCell:"B120",priceCell:"F130",description:"Eski boyalı yüzeylere macun ve astar uygulanarak iki kat sentetik esaslı mat boya yapılması (iç cephe)",surface:"old_painted",paintType:"synthetic_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:32.9515,laborCostM2:82.5,primerMaterialCostM2:10.08,priceM2:138.5418},
  {id:"B133_F142",summaryRow:15,nameCell:"B133",priceCell:"F142",description:"Yeni sıva yüzeylere macun ve astar uygulanarak iki kat Su bazlı Silikonlu Mat İç Cephe Boyası",surface:"new_plaster",paintType:"silicone_matte",coats:2,widePuttyInputIncluded:true,materialCostM2:52.97,laborCostM2:92.5,primerMaterialCostM2:5.46,priceM2:174.564},
  {id:"B145_F154",summaryRow:16,nameCell:"B145",priceCell:"F154",description:"Yeni sıva yüzeylere macun ve astar uygulanarak iki kat Su bazlı  Silikonlu Soft Mat İç Cephe Boyası",surface:"new_plaster",paintType:"silicone_soft_matte",coats:2,widePuttyInputIncluded:true,materialCostM2:55.01,laborCostM2:92.5,primerMaterialCostM2:5.46,priceM2:177.012},
  {id:"B157_F166",summaryRow:17,nameCell:"B157",priceCell:"F166",description:"Yeni sıva yüzeylere macun ve astar uygulanarak iki kat Su bazlı Plastik Mat İç Cephe Boyası",surface:"new_plaster",paintType:"plastic_matte",coats:2,widePuttyInputIncluded:true,materialCostM2:50.45,laborCostM2:92.5,primerMaterialCostM2:5.46,priceM2:171.54},
  {id:"B169_F177",summaryRow:18,nameCell:"B169",priceCell:"F177",description:"Yeni sıva yüzeylere astar uygulanarak iki kat Su bazlı Silikonlu Mat İç Cephe Boyası",surface:"new_plaster",paintType:"silicone_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:26.65,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:106.98},
  {id:"B180_F188",summaryRow:19,nameCell:"B180",priceCell:"F188",description:"Yeni sıva yüzeylere astar uygulanarak iki kat Su bazlı  Silikonlu Soft Mat İç Cephe Boyası",surface:"new_plaster",paintType:"silicone_soft_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:30.81,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:111.972},
  {id:"B191_F199",summaryRow:20,nameCell:"B191",priceCell:"F199",description:"Yeni sıva yüzeylere astar uygulanarak iki kat Su bazlı Plastik Mat İç Cephe Boyası",surface:"new_plaster",paintType:"plastic_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:25.87,laborCostM2:62.5,primerMaterialCostM2:5.46,priceM2:106.044},
  {id:"B202_F209",summaryRow:21,nameCell:"B202",priceCell:"F209",description:"Saten alçılı ve alçıpanel yüzeylere astar uygulanarak iki kat Su bazlı  Silikonlu Soft Mat İç Cephe Boyası",surface:"satin_plaster_drywall",paintType:"silicone_soft_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:22.79,laborCostM2:55,primerMaterialCostM2:5.46,priceM2:93.348},
  {id:"B212_F219",summaryRow:22,nameCell:"B212",priceCell:"F219",description:"Saten alçılı ve alçıpanel yüzeylere astar uygulanarak iki kat Su bazlı Plastik Mat İç Cephe Boyası",surface:"satin_plaster_drywall",paintType:"plastic_matte",coats:2,widePuttyInputIncluded:false,materialCostM2:18.23,laborCostM2:55,primerMaterialCostM2:5.46,priceM2:87.876},
  {id:"B222_F231",summaryRow:23,nameCell:"B222",priceCell:"F231",description:"Eski boyalı tavan yüzeylere iki kat Su bazlı Tavan Boyası",surface:"old_painted_ceiling",paintType:"ceiling_water_based",coats:2,widePuttyInputIncluded:false,materialCostM2:20.2315,laborCostM2:62.5,primerMaterialCostM2:0.0,priceM2:99.2778},
  {id:"B234_F241",summaryRow:24,nameCell:"B234",priceCell:"F241",description:"Yeni sıvalı tavan yüzeylere iki kat Su bazlı Tavan Boyası",surface:"new_plaster_ceiling",paintType:"ceiling_water_based",coats:2,widePuttyInputIncluded:false,materialCostM2:18.05,laborCostM2:75,primerMaterialCostM2:5.46,priceM2:111.66},
  {id:"B244_F252",summaryRow:25,nameCell:"B244",priceCell:"F252",description:"Saten alçılı tavan yüzeylere iki kat Su bazlı Tavan Boyası",surface:"satin_plaster_ceiling",paintType:"ceiling_water_based",coats:2,widePuttyInputIncluded:false,materialCostM2:20.0,laborCostM2:62.5,primerMaterialCostM2:0.0,priceM2:99},
];
export const OLD_PAINTED_CEILING_POZ=PAINTING_POSITIONS.find(p=>p.summaryRow===23)!;
