-- Teknik-O Stage 3: Baymak için açıklama + işlem kaynaklı olası teknik arıza noktaları.
-- Bir kontrol noktası kesin parça arızası değil, kaynağın bu hata ile ilişkilendirdiği olası adaydır.
-- Ham açıklama, işlem, URL ve her adayın exact support phrase'i transaction içinde doğrulanır.
-- Üretici araştırması veya canlı veritabanı çağrısı yapılmadan 20260927000021_seed_baymak_fault_candidates.sql üretildi.
BEGIN;

CREATE TEMP TABLE stage3_candidate_seed (
  brand text NOT NULL, official_model text NOT NULL, error_code text NOT NULL,
  candidate_key text NOT NULL, candidate_name text NOT NULL, fault_class text NOT NULL,
  evidence_description text NOT NULL, evidence_action text NOT NULL,
  evidence_url text NOT NULL, evidence_source_type text NOT NULL,
  description_support text NOT NULL, action_support text NOT NULL,
  description_token text NOT NULL, action_token text NOT NULL,
  PRIMARY KEY (candidate_key),
  CHECK (description_support <> '' OR action_support <> '')
) ON COMMIT DROP;

INSERT INTO stage3_candidate_seed VALUES
  ('Baymak', 'DUOTEC 33', 'E09', 'stage3_baymak_7bd5491daa724d5f54ef', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'DUOTEC 33', 'E12', 'stage3_baymak_2a4511847cc15484b841', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Baymak', 'DUOTEC 33', 'E15', 'stage3_baymak_0a930b26b1b5806c267f', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 33', 'E16', 'stage3_baymak_157e07d211fb7744e930', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 33', 'E17', 'stage3_baymak_81958b44d3efbbecd3fd', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 33', 'E18', 'stage3_baymak_39242c952e8c0b70ae78', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Baymak', 'DUOTEC 33', 'E18', 'stage3_baymak_e17fc49b659c1439d1d4', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 33', 'E21', 'stage3_baymak_cfcd4f7316ad9a8f8884', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'DUOTEC 33', 'E33', 'stage3_baymak_78b2355574b6c64c98c5', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 33', 'E35', 'stage3_baymak_a2a138598e03af7f407c', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 33', 'F34', 'stage3_baymak_40006284714acbb7e266', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Baymak', 'DUOTEC 33', 'F37', 'stage3_baymak_00ddf99aa0592910e9ed', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 33', 'F39', 'stage3_baymak_45097efad9299d2a5ba9', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 33', 'F40', 'stage3_baymak_94097e18f3ad2846d321', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 33', 'F43', 'stage3_baymak_3c8802140b2d888449d7', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 33', 'F47', 'stage3_baymak_8728b441e7e749a2e13f', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Baymak', 'DUOTEC 33', 'F50', 'stage3_baymak_3453cdb102e7dd9b9ef4', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Baymak', 'DUOTEC 33', 'F51', 'stage3_baymak_cbdba1d6f668598140a9', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 33', 'F52', 'stage3_baymak_e1310875ea6e484b03e7', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Baymak', 'DUOTEC 33', 'F53', 'stage3_baymak_646a2b77131fc6cba7a6', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Baymak', 'DUOTEC 33', 'F81', 'stage3_baymak_4f40eb7e990e24f6934d', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 42', 'E09', 'stage3_baymak_b27165e80163b5dcd4a8', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'DUOTEC 42', 'E12', 'stage3_baymak_51c92e02416ff2581e73', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Baymak', 'DUOTEC 42', 'E15', 'stage3_baymak_85de8da67ce1bb5b12fa', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 42', 'E16', 'stage3_baymak_952f1ae702f935232141', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 42', 'E17', 'stage3_baymak_e72c505b0b3e4ff45a6b', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 42', 'E18', 'stage3_baymak_924bf99c36c2c26e56ae', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Baymak', 'DUOTEC 42', 'E18', 'stage3_baymak_764b4f68f3dc53c6a176', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 42', 'E21', 'stage3_baymak_6df3ecafdb8fd7d4362d', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'DUOTEC 42', 'E33', 'stage3_baymak_6f8ebf187f3b7ac112c0', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 42', 'E35', 'stage3_baymak_889abf7fe19a6cb8709b', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 42', 'F34', 'stage3_baymak_b94de5676449dd1dac5f', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Baymak', 'DUOTEC 42', 'F37', 'stage3_baymak_70b82d81e9d9c6743e33', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 42', 'F39', 'stage3_baymak_79dab54a643b458e8f4a', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 42', 'F40', 'stage3_baymak_8a300f2971ce90b0d980', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 42', 'F43', 'stage3_baymak_f8ff7961d3b387f44bf2', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 42', 'F47', 'stage3_baymak_929965c41d53edb50b08', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Baymak', 'DUOTEC 42', 'F50', 'stage3_baymak_e0cc07ac85cdb69da913', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Baymak', 'DUOTEC 42', 'F51', 'stage3_baymak_5ec18f2ab7313f395d58', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 42', 'F52', 'stage3_baymak_6460e5604759213c749a', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Baymak', 'DUOTEC 42', 'F53', 'stage3_baymak_fccd2ace51738d8948df', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Baymak', 'DUOTEC 42', 'F81', 'stage3_baymak_41ad8a8c2e5c8a3e0ab3', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 45', 'E09', 'stage3_baymak_6ec17e8f8703110a8f99', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'DUOTEC 45', 'E12', 'stage3_baymak_cfc5dbd4198df0946f82', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Baymak', 'DUOTEC 45', 'E15', 'stage3_baymak_8f0769d6b75c0a4e077d', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 45', 'E16', 'stage3_baymak_a386768a1b95b0092f12', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 45', 'E17', 'stage3_baymak_7649c1ca36d3f119f19b', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 45', 'E18', 'stage3_baymak_197b1c8ef4f1718ec026', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Baymak', 'DUOTEC 45', 'E18', 'stage3_baymak_e9dd9f9328648fc59bf9', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 45', 'E21', 'stage3_baymak_d444f0a9fb5228f51004', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'DUOTEC 45', 'E33', 'stage3_baymak_634005f349cebd86b3a0', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 45', 'E35', 'stage3_baymak_cf2f7344e9eedf08f0c5', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 45', 'F34', 'stage3_baymak_2eae7c90dd342c2f20eb', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Baymak', 'DUOTEC 45', 'F37', 'stage3_baymak_8b694df7a1ea15fb6d40', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 45', 'F39', 'stage3_baymak_75bea9d8e9f6a58baffb', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 45', 'F40', 'stage3_baymak_906e9e5bf0a2f8b349da', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 45', 'F43', 'stage3_baymak_e97129e746d20b9944ce', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 45', 'F47', 'stage3_baymak_9c16d4adef00b353a776', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Baymak', 'DUOTEC 45', 'F50', 'stage3_baymak_3e86cc4d6e4ee275b8d1', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Baymak', 'DUOTEC 45', 'F51', 'stage3_baymak_97dfd1c76ef5c633d9cf', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 45', 'F52', 'stage3_baymak_ccb8a76c97a9fee4d591', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Baymak', 'DUOTEC 45', 'F53', 'stage3_baymak_8b5d81be9c5e7cae5bca', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Baymak', 'DUOTEC 45', 'F81', 'stage3_baymak_4935ba0f217012708754', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/4994/baymak-duotec-33-42-45.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E09', 'stage3_baymak_faefc5a07eed3c3d7d1a', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E12', 'stage3_baymak_cbcedc9071eccaa12893', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E15', 'stage3_baymak_8ba7b5de0f7809398559', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E16', 'stage3_baymak_6b9eb9b77a0db57f6363', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E17', 'stage3_baymak_9b544e9a429f262200cf', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E18', 'stage3_baymak_939cd546c70e75c6b2c0', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E18', 'stage3_baymak_5a1bb5647d7908e64b60', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E21', 'stage3_baymak_c117b630ab44f6432130', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E33', 'stage3_baymak_86c9c739994cf26556a2', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'E35', 'stage3_baymak_54e96fb24d2477078a8d', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F34', 'stage3_baymak_0d5735863cd5fa0f95a0', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F37', 'stage3_baymak_44181737d4c3c774ed60', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Tesisat basıncını yaklaşık 1–1,5 bar aralığına tamamlayın; su kaçağı olup olmadığını kontrol edin.', 'https://www.baymak.com.tr/kullanici-rehberi/duotec-compact-tam-yogusmali-kombi-su-dolumu-kullanici-rehberi', 'official_manufacturer', 'Düşük su basıncı', 'Tesisat basıncını yaklaşık 1–1,5 bar aralığına tamamlayın; su kaçağı olup olmadığını kontrol edin.', 'su basıncı', 'Tesisat basıncını'),
  ('Baymak', 'DUOTEC COMPACT 24', 'F39', 'stage3_baymak_87b35355e6daab0eccdb', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F40', 'stage3_baymak_49bf421e4b661bd3464a', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F43', 'stage3_baymak_f30dacf013109e141a13', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F47', 'stage3_baymak_b857752638ef3b1c28ed', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F50', 'stage3_baymak_ade29ce57e42f51e0128', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F51', 'stage3_baymak_32a353a58e57a1d5061b', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F52', 'stage3_baymak_cbe6a3a5ff31ed7bf9cf', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F53', 'stage3_baymak_30db673d4b259fef97d8', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Baymak', 'DUOTEC COMPACT 24', 'F81', 'stage3_baymak_e7ed1fe6758ab503a990', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E09', 'stage3_baymak_e4cd4cde66de9162d66c', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E12', 'stage3_baymak_bd3b902726a2430c0cc7', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E15', 'stage3_baymak_600673a64fda84014b77', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E16', 'stage3_baymak_7afff23587e48d4f222b', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E17', 'stage3_baymak_6fbd614d2d5aa6415fbd', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E18', 'stage3_baymak_aac3d5b11b6f5f71a2ca', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E18', 'stage3_baymak_c43379b8175313ced03b', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E21', 'stage3_baymak_9628e5be1dc6b2d8bbc5', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E33', 'stage3_baymak_93b397fb0007edd5afb8', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'E35', 'stage3_baymak_885d9b6bb09f24470188', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F34', 'stage3_baymak_1cfc8a76112d15849141', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F37', 'stage3_baymak_a8c9261ab7d2a0adc429', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Tesisat basıncını yaklaşık 1–1,5 bar aralığına tamamlayın; su kaçağı olup olmadığını kontrol edin.', 'https://www.baymak.com.tr/kullanici-rehberi/duotec-compact-tam-yogusmali-kombi-su-dolumu-kullanici-rehberi', 'official_manufacturer', 'Düşük su basıncı', 'Tesisat basıncını yaklaşık 1–1,5 bar aralığına tamamlayın; su kaçağı olup olmadığını kontrol edin.', 'su basıncı', 'Tesisat basıncını'),
  ('Baymak', 'DUOTEC COMPACT 30', 'F39', 'stage3_baymak_a4593d549b193aed415f', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F40', 'stage3_baymak_1a486d310909ad9b60de', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F43', 'stage3_baymak_225286af96fa2779479d', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F47', 'stage3_baymak_856df511effa8a807b8c', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F50', 'stage3_baymak_21817b26bbecaaa8e196', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F51', 'stage3_baymak_2b335f0822e0235a1d21', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F52', 'stage3_baymak_16822ff256bf48cf23df', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F53', 'stage3_baymak_77691e3fc76d620ee0de', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Baymak', 'DUOTEC COMPACT 30', 'F81', 'stage3_baymak_a39689fb6c8a13e8447c', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/6460/baymak-duotec-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E09', 'stage3_baymak_b5569b2b76918c21264f', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E12', 'stage3_baymak_4b02cfc6034f28046ffb', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E15', 'stage3_baymak_a3a98bc6bbcae34b3ba9', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E16', 'stage3_baymak_9f90a879242ffe95607f', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E17', 'stage3_baymak_499bf88383efdd7043c2', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E18', 'stage3_baymak_347f9f6d7dc8da906938', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E18', 'stage3_baymak_57476f6c9ad1fbfc8a7a', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E21', 'stage3_baymak_cfe938e50e0ac19ac39d', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E33', 'stage3_baymak_e7b6c28d387a0657782f', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'E35', 'stage3_baymak_321ed9b8e19665fa848a', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F34', 'stage3_baymak_bf01a5e589d6b0c1d954', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F37', 'stage3_baymak_cb92ddb1f02a94256b03', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F39', 'stage3_baymak_067bb5a15ea2dd80a0d9', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F40', 'stage3_baymak_37558ccba4a657bfb800', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F47', 'stage3_baymak_9b13b7500f1e8a623862', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F50', 'stage3_baymak_82ca7d4696dead702e6e', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F51', 'stage3_baymak_2a61a3bf66065d804a13', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F52', 'stage3_baymak_04b254f7a61086d05b80', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F53', 'stage3_baymak_7554bcee84d83ddcb79a', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Baymak', 'DUOTEC 42 DHW', 'F81', 'stage3_baymak_b128025363af814b0c2e', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'RESET tuşuna basın; sorun devam ederse Baymak Yetkili Servisi ile iletişime geçin.', 'https://www.baymak.com.tr/media/5477/baymak-duotec-dhw-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E04', 'stage3_baymak_e27b98c9c71b60b60fe0', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Hava basınç anahtarı arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Hava basınç anahtarı arızası', '', 'Hava basınç anahtarı', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E05', 'stage3_baymak_f5af284314d87d101fcd', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Hava basınç anahtarı arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Hava basınç anahtarı arızası', '', 'Hava basınç anahtarı', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E06', 'stage3_baymak_28c436c96b0ecb7cd271', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Hava basınç anahtarı arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Hava basınç anahtarı arızası', '', 'Hava basınç anahtarı', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E07', 'stage3_baymak_d0be1d7ca06540ea8134', 'Kablolama/soket/bağlantı sorunu', 'electrical', 'Baca termostat kablosu arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Baca termostat kablosu arızası', '', 'kablosu', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E08', 'stage3_baymak_c7831c39138c1cdd28c8', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E09', 'stage3_baymak_6d0b2ceb68c873205b64', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E12', 'stage3_baymak_5a2f0ea91f72895182ba', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'E21', 'stage3_baymak_53d0ee922d0e88b420de', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F22', 'stage3_baymak_dc498f415379aa9bf7f9', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük voltaj arızası', 'Besleme gerilimi normale döndüğünde cihaz arızadan çıkar.', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük voltaj arızası', 'Besleme gerilimi normale döndüğünde cihaz arızadan çıkar.', 'voltaj', 'Besleme gerilimi'),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F23', 'stage3_baymak_4a5c3fbd73466feffe1a', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Hava basınç anahtarı arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Hava basınç anahtarı arızası', '', 'Hava basınç anahtarı', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F25', 'stage3_baymak_aa892d89625159c1b130', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F31', 'stage3_baymak_26cd682bb9628bb3574b', 'Sıcaklık sensörü sorunu', 'sensor', 'Merkezi ısıtma NTC arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Merkezi ısıtma NTC arızası', '', 'NTC', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F32', 'stage3_baymak_7786f9716ea5f0cacf9d', 'Sensör sorunu', 'sensor', 'Dış hava sensörü arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensörü arızası', '', 'sensörü', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F33', 'stage3_baymak_54fd56fedf9df7751c70', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu NTC arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu NTC arızası', '', 'Kullanım suyu NTC', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F37', 'stage3_baymak_e109c16b93032897924f', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı arızası', 'Tesisat basıncını yükseltin; basınç yükseldiğinde cihaz arızadan çıkar.', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı arızası', '', 'su basıncı', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F40', 'stage3_baymak_4059250edc20006c16a0', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı arızası', '', 'su basıncı', ''),
  ('Baymak', 'LUNA AVANT 24 Fx', 'F59', 'stage3_baymak_8fb6ece1eac327f92b0f', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi modülasyon bobin arızası', '', 'https://www.baymak.com.tr/media/4057/baymak-luna-avant-24-fx-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi modülasyon bobin arızası', '', 'Gaz valfi', '');

DO $$
DECLARE v_bad bigint;
BEGIN
  IF (SELECT count(*) FROM public.official_error_codes_raw) <> 5879 THEN
    RAISE EXCEPTION 'Stage 3 stopped: official_error_codes_raw count is not 5879';
  END IF;
  IF (SELECT count(*) FROM stage3_candidate_seed) <> 142 THEN
    RAISE EXCEPTION 'Stage 3 stopped: baymak seed count differs from 142';
  END IF;
  SELECT count(*) INTO v_bad FROM stage3_candidate_seed s
  LEFT JOIN public.official_error_codes_raw r
    ON r.brand=s.brand AND r.official_model=s.official_model AND r.error_code=s.error_code
    AND r.official_description=s.evidence_description
    AND coalesce(r.official_action,'')=s.evidence_action AND r.source_url=s.evidence_url
  LEFT JOIN (
    SELECT m.id, m.official_model_name, f.brand
    FROM public.boiler_official_models m
    JOIN public.boiler_model_families f ON f.id=m.family_id
    WHERE m.is_active=true AND f.is_active=true
  ) model ON model.official_model_name=s.official_model AND model.brand=s.brand
  WHERE r.id IS NULL OR model.id IS NULL
    OR (s.description_support<>'' AND position(s.description_support in s.evidence_description)=0)
    OR (s.action_support<>'' AND position(s.action_support in s.evidence_action)=0)
    OR (s.description_support<>'' AND position(s.description_token in s.description_support)=0)
    OR (s.action_support<>'' AND position(s.action_token in s.action_support)=0);
  IF v_bad <> 0 THEN
    RAISE EXCEPTION 'Stage 3 stopped: baymak raw evidence, support phrase, or model identity differs';
  END IF;
  IF EXISTS (SELECT 1 FROM stage3_candidate_seed
      WHERE evidence_url !~ '^https://[^ ]+$' OR length(trim(candidate_name))=0
        OR evidence_source_type NOT IN ('official_manufacturer','trusted_third_party')
        OR fault_class NOT IN ('gas_supply','ignition','sensor','hydraulic','electrical','electronic',
                              'combustion_air','mechanical','installation','other')) THEN
    RAISE EXCEPTION 'Stage 3 stopped: invalid baymak seed fields';
  END IF;
  IF EXISTS (SELECT 1 FROM stage3_candidate_seed s JOIN public.boiler_fault_candidates c
      ON c.candidate_key=s.candidate_key WHERE c.verification_status<>'verified' OR c.is_active<>true
      OR c.candidate_name<>s.candidate_name OR c.evidence_url<>s.evidence_url) THEN
    RAISE EXCEPTION 'Stage 3 stopped: existing candidate key conflicts with seed';
  END IF;
END $$;

INSERT INTO public.boiler_fault_candidates (
  official_error_record_id,family_id,official_model_id,error_code,candidate_key,candidate_name,
  description,fault_class,verification_status,evidence_source_type,evidence_url,evidence_note,
  requires_service,customer_observable,is_active
)
SELECT r.id, f.id, m.id, s.error_code, s.candidate_key, s.candidate_name,
  'Kaynağın bu hatayla ilişkilendirdiği olası teknik arıza noktası: ' || s.candidate_name,
  s.fault_class, 'verified', s.evidence_source_type, r.source_url,
  concat_ws(E'\n',
    CASE WHEN s.description_support<>'' THEN 'description support: "' || s.description_token || '"; context: "' || s.description_support || '"' END,
    CASE WHEN s.action_support<>'' THEN 'action support: "' || s.action_token || '"; context: "' || s.action_support || '"' END),
  true, false, true
FROM stage3_candidate_seed s
JOIN public.official_error_codes_raw r
  ON r.brand=s.brand AND r.official_model=s.official_model AND r.error_code=s.error_code
  AND r.official_description=s.evidence_description
  AND coalesce(r.official_action,'')=s.evidence_action AND r.source_url=s.evidence_url
JOIN public.boiler_official_models m ON m.official_model_name=s.official_model AND m.is_active=true
JOIN public.boiler_model_families f ON f.id=m.family_id AND f.brand=s.brand AND f.is_active=true
WHERE NOT EXISTS (SELECT 1 FROM public.boiler_fault_candidates c WHERE c.candidate_key=s.candidate_key);

DO $$
DECLARE v_actual bigint;
BEGIN
  SELECT count(*) INTO v_actual FROM public.boiler_fault_candidates c
  JOIN stage3_candidate_seed s ON s.candidate_key=c.candidate_key
  JOIN public.boiler_official_models m ON m.id=c.official_model_id
  JOIN public.boiler_model_families f ON f.id=c.family_id
  WHERE f.brand=s.brand AND m.official_model_name=s.official_model AND c.error_code=s.error_code
    AND c.verification_status='verified' AND c.is_active=true
    AND c.evidence_source_type=s.evidence_source_type AND c.evidence_url=s.evidence_url
    AND length(trim(c.evidence_note))>0;
  IF v_actual <> 142 THEN
    RAISE EXCEPTION 'Stage 3 stopped: baymak expected 142 verified candidates, found %', v_actual;
  END IF;
END $$;
COMMIT;
