-- Teknik-O Stage 3: Lambert için açıklama + işlem kaynaklı olası teknik arıza noktaları.
-- Bir kontrol noktası kesin parça arızası değil, kaynağın bu hata ile ilişkilendirdiği olası adaydır.
-- Ham açıklama, işlem, URL ve her adayın exact support phrase'i transaction içinde doğrulanır.
-- Üretici araştırması veya canlı veritabanı çağrısı yapılmadan 20260927000024_seed_lambert_fault_candidates.sql üretildi.
BEGIN;

CREATE TEMP TABLE stage3_candidate_seed (
  brand text NOT NULL, official_model text NOT NULL, error_code text NOT NULL,
  candidate_key text NOT NULL, candidate_name text NOT NULL, fault_class text NOT NULL,
  evidence_description text NOT NULL, evidence_action text NOT NULL,
  evidence_url text NOT NULL, evidence_source_type text NOT NULL,
  description_support text NOT NULL, action_support text NOT NULL,
  description_token text NOT NULL, action_token text NOT NULL,
  PRIMARY KEY (candidate_key),
  CHECK (description_support <> '' OR action_support <> '')
) ON COMMIT DROP;

INSERT INTO stage3_candidate_seed VALUES
  ('Lambert', 'LPY 24 Fi', 'E09', 'stage3_lambert_a3b571f6dfe15e0763b2', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY 24 Fi', 'E12', 'stage3_lambert_eccd583b661b1289362e', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY 24 Fi', 'E15', 'stage3_lambert_38aec41eeac2af9db625', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'E16', 'stage3_lambert_0d1214c151fb942e8618', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'E17', 'stage3_lambert_6690024dee91fd93098a', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'E18', 'stage3_lambert_8f79bbcba84831462b7d', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY 24 Fi', 'E18', 'stage3_lambert_28a0dd1a19d99300f355', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'E21', 'stage3_lambert_1b392aee3355f532c197', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY 24 Fi', 'E33', 'stage3_lambert_1e3dd85bd16140696354', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY 24 Fi', 'E35', 'stage3_lambert_be9884199360cb3bb253', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY 24 Fi', 'F34', 'stage3_lambert_c76701e4d977174eeddb', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY 24 Fi', 'F37', 'stage3_lambert_fff1ac5678be8e4c4780', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY 24 Fi', 'F39', 'stage3_lambert_958822fff2a6210272ca', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'F40', 'stage3_lambert_73ddaedb5f12daaca0de', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 24 Fi', 'F43', 'stage3_lambert_0894028b7ebd28f146d9', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 24 Fi', 'F47', 'stage3_lambert_c44f36e7abc494112cc1', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY 24 Fi', 'F50', 'stage3_lambert_fea66ca3db696d91f872', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'F51', 'stage3_lambert_f6323ffb5bed3f7da715', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'F52', 'stage3_lambert_ba7c07a9bd5bacace1db', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY 24 Fi', 'F53', 'stage3_lambert_7236fe9e342e49cd3570', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY 24 Fi', 'F81', 'stage3_lambert_b4228840cdf30c4a50bb', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'E09', 'stage3_lambert_3c96f7fe2d16549b9473', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY 28 Fi', 'E12', 'stage3_lambert_20983d7f45b6b7863f18', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY 28 Fi', 'E15', 'stage3_lambert_a8bc256421141ba7c433', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'E16', 'stage3_lambert_99658232aecf97d1cb83', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'E17', 'stage3_lambert_5e8e6d438d2bec6daeb1', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'E18', 'stage3_lambert_639af516bbf46df87467', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY 28 Fi', 'E18', 'stage3_lambert_dd54843ed89a06c3fb0c', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'E21', 'stage3_lambert_ec9a7597e4eace781e10', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY 28 Fi', 'E33', 'stage3_lambert_e4ca90ebcb3967301104', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY 28 Fi', 'E35', 'stage3_lambert_56f60c9b125094573739', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY 28 Fi', 'F34', 'stage3_lambert_8175605ccc61f10ce784', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY 28 Fi', 'F37', 'stage3_lambert_97925b71a86adbf14109', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY 28 Fi', 'F39', 'stage3_lambert_a3bede0c0399b03ea50f', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'F40', 'stage3_lambert_d3ae94838b788c46a6e8', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 28 Fi', 'F43', 'stage3_lambert_a433828bb2ccb07653ee', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 28 Fi', 'F47', 'stage3_lambert_938322542d2531bd0131', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY 28 Fi', 'F50', 'stage3_lambert_8a854777035fe68f108f', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'F51', 'stage3_lambert_b8a9554aa7ea14a299ae', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'F52', 'stage3_lambert_81657cb86ed70d057fdb', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY 28 Fi', 'F53', 'stage3_lambert_573e8eadc4ada9c8d152', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY 28 Fi', 'F81', 'stage3_lambert_d1c5c65db9fd745e3bc9', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'E09', 'stage3_lambert_8c8febf40156026539e5', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY 33 Fi', 'E12', 'stage3_lambert_13cdd93e8523444acec1', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY 33 Fi', 'E15', 'stage3_lambert_4dc1a70e2aa8147b8b49', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'E16', 'stage3_lambert_4a7c98cac5b3cc968293', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'E17', 'stage3_lambert_b1ffe623a225d96e0739', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'E18', 'stage3_lambert_88140a008a77eee6cdcb', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY 33 Fi', 'E18', 'stage3_lambert_ca2db7b2f6cab91ec081', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'E21', 'stage3_lambert_d4eec2d3a0a89f83e508', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY 33 Fi', 'E33', 'stage3_lambert_7955585b7f5caafe3739', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY 33 Fi', 'E35', 'stage3_lambert_09a303e5f4b319ec872e', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY 33 Fi', 'F34', 'stage3_lambert_a1750f31a48fa2a8d160', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY 33 Fi', 'F37', 'stage3_lambert_b047a93500e49abc4817', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY 33 Fi', 'F39', 'stage3_lambert_5d691dfdc9e88b19141c', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'F40', 'stage3_lambert_a181b39bb37712353b1c', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 33 Fi', 'F43', 'stage3_lambert_9266749bcbef90c11d67', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 33 Fi', 'F47', 'stage3_lambert_c023ac6dc5b447524c9c', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY 33 Fi', 'F50', 'stage3_lambert_cb69d71c3751f711f9c3', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'F51', 'stage3_lambert_f6f5a5f7885090475b4b', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'F52', 'stage3_lambert_fab2fc9b47062b634773', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY 33 Fi', 'F53', 'stage3_lambert_290509f748781fbd0ae0', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY 33 Fi', 'F81', 'stage3_lambert_4f42c3aaf706276733cb', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'E09', 'stage3_lambert_9ea27bf9df5b972e9f13', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY 42 Fi', 'E12', 'stage3_lambert_9a6b99adecc5e5e8411e', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY 42 Fi', 'E15', 'stage3_lambert_e4a6f0555fa329043ad6', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'E16', 'stage3_lambert_ff2510104d0394d464e4', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'E17', 'stage3_lambert_87e32f36b5dc3cb15f27', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'E18', 'stage3_lambert_192ba17ae052fc4a3558', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY 42 Fi', 'E18', 'stage3_lambert_945423e7d83b3bc633a0', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'E21', 'stage3_lambert_557d6cdc9456b6b85d34', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY 42 Fi', 'E33', 'stage3_lambert_f5700928474105053b68', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY 42 Fi', 'E35', 'stage3_lambert_b52e9c2bb53a7c84777f', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY 42 Fi', 'F34', 'stage3_lambert_57556e162cdec299de30', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY 42 Fi', 'F37', 'stage3_lambert_5dba23f542a8a4bcc87b', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY 42 Fi', 'F39', 'stage3_lambert_1e5c58a08ef2282de953', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'F40', 'stage3_lambert_2068a63aabebe0e20f71', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 42 Fi', 'F43', 'stage3_lambert_72228c65805ed23909a3', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 42 Fi', 'F47', 'stage3_lambert_14ef7db0c57d4031ad2b', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY 42 Fi', 'F50', 'stage3_lambert_152125dad48b4b0e932c', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'F51', 'stage3_lambert_bb40b7c196fba0e5bc8f', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'F52', 'stage3_lambert_838e3d826658b22eb1cb', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY 42 Fi', 'F53', 'stage3_lambert_f531eeb216728a036887', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY 42 Fi', 'F81', 'stage3_lambert_634c16135eb0b9aa889f', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'E09', 'stage3_lambert_df307efe65170847a0c0', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY 45 Fi', 'E12', 'stage3_lambert_4c88d4b10db09566adb4', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY 45 Fi', 'E15', 'stage3_lambert_3475c5a2b4f83cb9b3bc', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'E16', 'stage3_lambert_d98e88c3906d45d2acb9', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'E17', 'stage3_lambert_7df2bdf457f86b21444c', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'E18', 'stage3_lambert_c63ad752eb42adc75e9f', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY 45 Fi', 'E18', 'stage3_lambert_b8217a957683c9b2a62a', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'E21', 'stage3_lambert_ba812ee69a08edd53b3a', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY 45 Fi', 'E33', 'stage3_lambert_06e344af9223f0848aa5', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY 45 Fi', 'E35', 'stage3_lambert_7f3991b7f52e22059ed9', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY 45 Fi', 'F34', 'stage3_lambert_40125e5460e527b578b9', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY 45 Fi', 'F37', 'stage3_lambert_9f2cf4bdb19a0d43befb', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY 45 Fi', 'F39', 'stage3_lambert_c1e369ca9dd31c068a8d', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'F40', 'stage3_lambert_f0d68a5ca8d9a17eaacc', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 45 Fi', 'F43', 'stage3_lambert_d3cd85e07f9a09611a31', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Otomatik doldurma sonrası düşük su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Otomatik doldurma sonrası düşük su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY 45 Fi', 'F47', 'stage3_lambert_efe20fa2da7fe9e8ba39', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY 45 Fi', 'F50', 'stage3_lambert_e3f48b323e2f6dc012d5', 'Boyler sıcaklık sensörü sorunu', 'sensor', 'Sıcak su boyler sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sıcak su boyler sensör arızası', '', 'boyler sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'F51', 'stage3_lambert_d62be5f056f41579d554', 'Sensör sorunu', 'sensor', 'PT1000 sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'PT1000 sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'F52', 'stage3_lambert_12afd4a7f5ad8cf085f6', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY 45 Fi', 'F53', 'stage3_lambert_7c79d3009b8dd1e39091', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör ısı sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör ısı sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY 45 Fi', 'F81', 'stage3_lambert_ad3264f6084c93893c99', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/3917/lambert-lpy-serisi-premix-teknolojili-yogusmali-kombiler-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'LPY Compact 24', 'E09', 'stage3_lambert_8074c1c6dc5d6b397f9b', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY Compact 24', 'E12', 'stage3_lambert_ea815d5138a6fbe37d78', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY Compact 24', 'E15', 'stage3_lambert_8a3d6613d37f48caf324', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY Compact 24', 'E16', 'stage3_lambert_6d2374d73d9da88ffcb5', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY Compact 24', 'E17', 'stage3_lambert_d33bda6581bdcc3d27ef', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY Compact 24', 'E18', 'stage3_lambert_a00e0037913d8fcd7a21', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY Compact 24', 'E18', 'stage3_lambert_8f20de7d7c3dcf2bc673', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY Compact 24', 'E21', 'stage3_lambert_230b5e254664bf913b86', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY Compact 24', 'E33', 'stage3_lambert_bf217e78c825242eb5fa', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY Compact 24', 'E35', 'stage3_lambert_5ccda77ecee077270226', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY Compact 24', 'F34', 'stage3_lambert_b6b1c7e4f9966727583c', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY Compact 24', 'F37', 'stage3_lambert_38fb7b89812f552d6adb', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY Compact 24', 'F39', 'stage3_lambert_28468bed15d925f63447', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY Compact 24', 'F40', 'stage3_lambert_8088e40c1b9b86516391', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY Compact 24', 'F47', 'stage3_lambert_25b466c214986a3d9b9a', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY Compact 24', 'F52', 'stage3_lambert_432401cbd47340515672', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY Compact 24', 'F53', 'stage3_lambert_bad4217c813705c1a32c', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör termal sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör termal sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY Compact 24', 'F81', 'stage3_lambert_af60a28ed84579fa19f5', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'LPY Compact 30', 'E09', 'stage3_lambert_22d7f8e49cd38b2f2977', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'LPY Compact 30', 'E12', 'stage3_lambert_d510844eeba7f1119789', 'Kodlama/EEPROM sorunu', 'electronic', 'EEPROM (yazılım) arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'EEPROM (yazılım) arızası', '', 'EEPROM', ''),
  ('Lambert', 'LPY Compact 30', 'E15', 'stage3_lambert_3ef747664a725b792f64', 'Sensör sorunu', 'sensor', 'Sensör sıcaklık değişim hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör sıcaklık değişim hatası', '', 'Sensör', ''),
  ('Lambert', 'LPY Compact 30', 'E16', 'stage3_lambert_6f163745b5986ea29d3d', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensör kilitlenme hatası', '', 'Dönüş sıcaklık sensör', ''),
  ('Lambert', 'LPY Compact 30', 'E17', 'stage3_lambert_a963c4a87580fb32dd78', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensör kilitlenme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensör kilitlenme hatası', '', 'Çıkış sıcaklık sensör', ''),
  ('Lambert', 'LPY Compact 30', 'E18', 'stage3_lambert_764ba43deeb3f9fcbf8f', 'Sıcaklık sensörü sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'NTC', ''),
  ('Lambert', 'LPY Compact 30', 'E18', 'stage3_lambert_966e5865f488eb5f6e7d', 'Sensör sorunu', 'sensor', 'NTC sensör test hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'NTC sensör test hatası', '', 'sensör', ''),
  ('Lambert', 'LPY Compact 30', 'E21', 'stage3_lambert_693a3e42d1fc999cedb6', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'LPY Compact 30', 'E33', 'stage3_lambert_670c6c7a599629a75fd9', 'Dönüş sıcaklık sensörü sorunu', 'sensor', 'Dönüş sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dönüş sıcaklık sensörü arızası', '', 'Dönüş sıcaklık sensörü', ''),
  ('Lambert', 'LPY Compact 30', 'E35', 'stage3_lambert_62ed95510c42d674b3a6', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Çıkış sıcaklık sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış sıcaklık sensörü arızası', '', 'Çıkış sıcaklık sensörü', ''),
  ('Lambert', 'LPY Compact 30', 'F34', 'stage3_lambert_5f174ed263bd33502330', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük besleme gerilimi', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük besleme gerilimi', '', 'besleme gerilimi', ''),
  ('Lambert', 'LPY Compact 30', 'F37', 'stage3_lambert_8e311ca7f7e30ddaed6b', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'LPY Compact 30', 'F39', 'stage3_lambert_ba397229eb718ec2a03b', 'Sensör sorunu', 'sensor', 'Dış hava sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Dış hava sensör arızası', '', 'sensör', ''),
  ('Lambert', 'LPY Compact 30', 'F40', 'stage3_lambert_952975f73ee4d3e435fb', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Yüksek su basıncı', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Yüksek su basıncı', '', 'su basıncı', ''),
  ('Lambert', 'LPY Compact 30', 'F47', 'stage3_lambert_665dd70beb43583e5582', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Su basınç anahtarı bağlı değil', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Su basınç anahtarı bağlı değil', '', 'Su basınç', ''),
  ('Lambert', 'LPY Compact 30', 'F52', 'stage3_lambert_c2f45006b5e2e24f11d0', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'LPY Compact 30', 'F53', 'stage3_lambert_77c5a4d6f461a18c199d', 'Eşanjör/ısı bloğu sorunu', 'hydraulic', 'Ana eşanjör termal sigortası arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Ana eşanjör termal sigortası arızası', '', 'eşanjör', ''),
  ('Lambert', 'LPY Compact 30', 'F81', 'stage3_lambert_b876095121cc91737159', 'Sensör sorunu', 'sensor', 'Sensör test arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/5264/lambert-lpy-compact-tam-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Sensör test arızası', '', 'Sensör', ''),
  ('Lambert', 'Attivo 240', 'E04', 'stage3_lambert_4de02fceeeca836b00fd', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 240', 'E05', 'stage3_lambert_200b285863ac879fd41a', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 240', 'E06', 'stage3_lambert_d78967ca75740dfde5c8', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 240', 'E07', 'stage3_lambert_69a079ac02ee9f63e4d4', 'Termostat/sıcaklık sınırlayıcısı sorunu', 'sensor', 'TTB termostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'TTB termostat arızası', '', ' termostat', ''),
  ('Lambert', 'Attivo 240', 'E09', 'stage3_lambert_a84118814f7b0b79252a', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Gaz valfi geri besleme arızası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 240', 'E12', 'stage3_lambert_28e4c07cbab49fd5f76b', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 240', 'E21', 'stage3_lambert_a0e4fc9deb87674c4e66', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 240', 'F22', 'stage3_lambert_c4d4867be4d4391179a3', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük voltaj arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Düşük voltaj arızası', '', 'voltaj', ''),
  ('Lambert', 'Attivo 240', 'F23', 'stage3_lambert_d7949c3f9a9f46b49570', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 240', 'F25', 'stage3_lambert_e9e2ebc073cb5a8ec83c', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 240', 'F31', 'stage3_lambert_4702cd201ccc303fdcd9', 'Sıcaklık sensörü sorunu', 'sensor', 'Merkezi ısıtma NTC sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Merkezi ısıtma NTC sensör arızası', '', 'NTC', ''),
  ('Lambert', 'Attivo 240', 'F31', 'stage3_lambert_4831bb3644651265d105', 'Sensör sorunu', 'sensor', 'Merkezi ısıtma NTC sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Merkezi ısıtma NTC sensör arızası', '', 'sensör', ''),
  ('Lambert', 'Attivo 240', 'F32', 'stage3_lambert_b3e975f139eb8f3f958e', 'Sensör sorunu', 'sensor', 'Dış hava sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Dış hava sensörü arızası', '', 'sensörü', ''),
  ('Lambert', 'Attivo 240', 'F33', 'stage3_lambert_ab356376ad756ee1a891', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu NTC sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Kullanım suyu NTC sensör arızası', '', 'Kullanım suyu NTC', ''),
  ('Lambert', 'Attivo 240', 'F37', 'stage3_lambert_a1bd49a5cfc5c23f37c7', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basınç arızası', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Düşük su basınç arızası', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basınç', 'su basıncını'),
  ('Lambert', 'Attivo 240', 'F59', 'stage3_lambert_fd6366bb490c59778e53', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Gaz valfi arızası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 310', 'E04', 'stage3_lambert_bd3c22005e8d7c1a166c', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 310', 'E05', 'stage3_lambert_0950c1fa45b7ae65527f', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 310', 'E06', 'stage3_lambert_eca42eac928e4e652eac', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 310', 'E07', 'stage3_lambert_ba9d8d1fdf761559a40a', 'Termostat/sıcaklık sınırlayıcısı sorunu', 'sensor', 'TTB termostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'TTB termostat arızası', '', ' termostat', ''),
  ('Lambert', 'Attivo 310', 'E09', 'stage3_lambert_6efb159e7024361c66ef', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Gaz valfi geri besleme arızası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 310', 'E12', 'stage3_lambert_74855660852a2c8d0ff3', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 310', 'E21', 'stage3_lambert_251300e047f000a25b64', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 310', 'F22', 'stage3_lambert_574a8573f209c0948a88', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük voltaj arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Düşük voltaj arızası', '', 'voltaj', ''),
  ('Lambert', 'Attivo 310', 'F23', 'stage3_lambert_90e370704e3390980d7a', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Presostat arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Presostat arızası', '', 'Presostat', ''),
  ('Lambert', 'Attivo 310', 'F25', 'stage3_lambert_fc1c12c8b47995985e65', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 310', 'F31', 'stage3_lambert_90a8a2f15c181c7985a4', 'Sıcaklık sensörü sorunu', 'sensor', 'Merkezi ısıtma NTC sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Merkezi ısıtma NTC sensör arızası', '', 'NTC', ''),
  ('Lambert', 'Attivo 310', 'F31', 'stage3_lambert_8294f8ff21584c5f1f33', 'Sensör sorunu', 'sensor', 'Merkezi ısıtma NTC sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Merkezi ısıtma NTC sensör arızası', '', 'sensör', ''),
  ('Lambert', 'Attivo 310', 'F32', 'stage3_lambert_c636a6143f4b2e2c342e', 'Sensör sorunu', 'sensor', 'Dış hava sensörü arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Dış hava sensörü arızası', '', 'sensörü', ''),
  ('Lambert', 'Attivo 310', 'F33', 'stage3_lambert_cd6a1eb807372648dd78', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu NTC sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Kullanım suyu NTC sensör arızası', '', 'Kullanım suyu NTC', ''),
  ('Lambert', 'Attivo 310', 'F37', 'stage3_lambert_726ee2683585cc10928f', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basınç arızası', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Düşük su basınç arızası', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basınç', 'su basıncını'),
  ('Lambert', 'Attivo 310', 'F59', 'stage3_lambert_48c405d4f702b6c558f1', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/2900/300032131-kullanma-kilavuzu-lambert-attivo_tr_r2.pdf', 'official_manufacturer', 'Gaz valfi arızası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 24 LN', 'E03', 'stage3_lambert_fd042a75d830c8b27dda', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Hava basınç anahtarı arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Hava basınç anahtarı arızası', '', 'Hava basınç anahtarı', ''),
  ('Lambert', 'Attivo 24 LN', 'E05', 'stage3_lambert_20b849a5d92bf30e8763', 'Sıcaklık sensörü sorunu', 'sensor', 'Merkezi ısıtma NTC arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Merkezi ısıtma NTC arızası', '', 'NTC', ''),
  ('Lambert', 'Attivo 24 LN', 'E06', 'stage3_lambert_89a1a9e757d3a63829d3', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'Attivo 24 LN', 'E09', 'stage3_lambert_6ac71e754f1dc55be4b5', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi geri besleme hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi geri besleme hatası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 24 LN', 'E10', 'stage3_lambert_3ea7b6a22c268ff0b266', 'Tesisat su basıncı/eksik su sorunu', 'hydraulic', 'Düşük su basıncı arızası', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük su basıncı arızası', 'Sistem su basıncını kontrol edip gerektiğinde sistemi yeniden basınçlandırın; sorun sürerse yetkili servisi arayın.', 'su basıncı', 'su basıncını'),
  ('Lambert', 'Attivo 24 LN', 'E21', 'stage3_lambert_b4a2fbc7c8ac416e7963', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 24 LN', 'E25', 'stage3_lambert_c8df28c2ec30e299ade9', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 24 LN', 'E32', 'stage3_lambert_5e8729633219546e21b3', 'Sensör sorunu', 'sensor', 'OTC sensörü hatası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'OTC sensörü hatası', '', 'sensörü', ''),
  ('Lambert', 'Attivo 24 LN', 'E59', 'stage3_lambert_7b6556ca059c1feb63f8', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi modülasyon bobin arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi modülasyon bobin arızası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 24 LN', 'E96', 'stage3_lambert_ca69ed89aab5cd767155', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük voltaj arızası', 'Cihazı resetleyin; sorun devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4864/lambert-attivo-24-ln-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük voltaj arızası', '', 'voltaj', ''),
  ('Lambert', 'Attivo 24 Fx', 'E06', 'stage3_lambert_28800515e46d515a4943', 'Termostat/sıcaklık sınırlayıcısı sorunu', 'sensor', 'Emniyet termostatı arızası', 'Cihazı resetleyin; arıza devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Emniyet termostatı arızası', '', 'Emniyet termostatı', ''),
  ('Lambert', 'Attivo 24 Fx', 'E08', 'stage3_lambert_b6d0b5cb2f640316a525', 'Hava basınç şalteri/sensörü sorunu', 'sensor', 'Hava basınç anahtarı arızası', 'Arıza devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Hava basınç anahtarı arızası', '', 'Hava basınç anahtarı', ''),
  ('Lambert', 'Attivo 24 Fx', 'E09', 'stage3_lambert_39450769d8064d518ba3', 'Sensör sorunu', 'sensor', 'Çıkış suyu sensör arızası', 'Arıza devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Çıkış suyu sensör arızası', '', 'sensör', ''),
  ('Lambert', 'Attivo 24 Fx', 'E10', 'stage3_lambert_6b42a7652e4337e8948d', 'Kullanım suyu sıcaklık sensörü sorunu', 'sensor', 'Kullanım suyu sensör arızası', 'Arıza devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Kullanım suyu sensör arızası', '', 'Kullanım suyu sensör', ''),
  ('Lambert', 'Attivo 24 Fx', 'E21', 'stage3_lambert_40e0e2cbe58a7049382a', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Yetkili servise başvurun.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 24 Fx', 'E25', 'stage3_lambert_52352c762d9fc303994b', 'Elektronik kart/kontrol ünitesi sorunu', 'electronic', 'Elektronik kart arızası', 'Arıza devam ederse yetkili servisi arayın.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Elektronik kart arızası', '', 'Elektronik kart', ''),
  ('Lambert', 'Attivo 24 Fx', 'E32', 'stage3_lambert_2c023be4509a5df49b4e', 'Sensör sorunu', 'sensor', 'OTC sensörü hatası', 'Sensör normal çalışma aralığına döndüğünde hata gider; devam ederse yetkili servise başvurun.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'OTC sensörü hatası', 'Sensör normal çalışma aralığına döndüğünde hata gider', 'sensörü', 'Sensör'),
  ('Lambert', 'Attivo 24 Fx', 'E59', 'stage3_lambert_9a06e62c4632c82d6630', 'Gaz valfi/armatürü sorunu', 'gas_supply', 'Gaz valfi modülasyon bobin arızası', 'Yetkili servise başvurun.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Gaz valfi modülasyon bobin arızası', '', 'Gaz valfi', ''),
  ('Lambert', 'Attivo 24 Fx', 'E96', 'stage3_lambert_156f3b58c09bfaf3af84', 'Elektrik besleme/gerilim sorunu', 'electrical', 'Düşük voltaj arızası', 'Besleme gerilimi normale döndüğünde cihaz arızadan kendiliğinden çıkar.', 'https://www.baymak.com.tr/media/4078/lambert-attivo-24-fx-3-esanjorlu-yogusmali-kombi-kullanma-kilavuzu.pdf', 'official_manufacturer', 'Düşük voltaj arızası', 'Besleme gerilimi normale döndüğünde cihaz arızadan kendiliğinden çıkar.', 'voltaj', 'Besleme gerilimi');

DO $$
DECLARE v_bad bigint;
BEGIN
  IF (SELECT count(*) FROM public.official_error_codes_raw) <> 5879 THEN
    RAISE EXCEPTION 'Stage 3 stopped: official_error_codes_raw count is not 5879';
  END IF;
  IF (SELECT count(*) FROM stage3_candidate_seed) <> 192 THEN
    RAISE EXCEPTION 'Stage 3 stopped: lambert seed count differs from 192';
  END IF;
  SELECT count(*) INTO v_bad FROM stage3_candidate_seed s
  LEFT JOIN public.official_error_codes_raw r
    ON r.brand=s.brand AND r.official_model=s.official_model AND r.error_code=s.error_code
    AND r.official_description=s.evidence_description
    AND coalesce(r.official_action,'')=s.evidence_action AND r.source_url=s.evidence_url
  LEFT JOIN (
    SELECT m.id, m.official_model_name, f.brand
    FROM public.boiler_official_models m
    JOIN public.boiler_model_families f ON f.id=m.family_id
    WHERE m.is_active=true AND f.is_active=true
  ) model ON model.official_model_name=s.official_model AND model.brand=s.brand
  WHERE r.id IS NULL OR model.id IS NULL
    OR (s.description_support<>'' AND position(s.description_support in s.evidence_description)=0)
    OR (s.action_support<>'' AND position(s.action_support in s.evidence_action)=0)
    OR (s.description_support<>'' AND position(s.description_token in s.description_support)=0)
    OR (s.action_support<>'' AND position(s.action_token in s.action_support)=0);
  IF v_bad <> 0 THEN
    RAISE EXCEPTION 'Stage 3 stopped: lambert raw evidence, support phrase, or model identity differs';
  END IF;
  IF EXISTS (SELECT 1 FROM stage3_candidate_seed
      WHERE evidence_url !~ '^https://[^ ]+$' OR length(trim(candidate_name))=0
        OR evidence_source_type NOT IN ('official_manufacturer','trusted_third_party')
        OR fault_class NOT IN ('gas_supply','ignition','sensor','hydraulic','electrical','electronic',
                              'combustion_air','mechanical','installation','other')) THEN
    RAISE EXCEPTION 'Stage 3 stopped: invalid lambert seed fields';
  END IF;
  IF EXISTS (SELECT 1 FROM stage3_candidate_seed s JOIN public.boiler_fault_candidates c
      ON c.candidate_key=s.candidate_key WHERE c.verification_status<>'verified' OR c.is_active<>true
      OR c.candidate_name<>s.candidate_name OR c.evidence_url<>s.evidence_url) THEN
    RAISE EXCEPTION 'Stage 3 stopped: existing candidate key conflicts with seed';
  END IF;
END $$;

INSERT INTO public.boiler_fault_candidates (
  official_error_record_id,family_id,official_model_id,error_code,candidate_key,candidate_name,
  description,fault_class,verification_status,evidence_source_type,evidence_url,evidence_note,
  requires_service,customer_observable,is_active
)
SELECT r.id, f.id, m.id, s.error_code, s.candidate_key, s.candidate_name,
  'Kaynağın bu hatayla ilişkilendirdiği olası teknik arıza noktası: ' || s.candidate_name,
  s.fault_class, 'verified', s.evidence_source_type, r.source_url,
  concat_ws(E'\n',
    CASE WHEN s.description_support<>'' THEN 'description support: "' || s.description_token || '"; context: "' || s.description_support || '"' END,
    CASE WHEN s.action_support<>'' THEN 'action support: "' || s.action_token || '"; context: "' || s.action_support || '"' END),
  true, false, true
FROM stage3_candidate_seed s
JOIN public.official_error_codes_raw r
  ON r.brand=s.brand AND r.official_model=s.official_model AND r.error_code=s.error_code
  AND r.official_description=s.evidence_description
  AND coalesce(r.official_action,'')=s.evidence_action AND r.source_url=s.evidence_url
JOIN public.boiler_official_models m ON m.official_model_name=s.official_model AND m.is_active=true
JOIN public.boiler_model_families f ON f.id=m.family_id AND f.brand=s.brand AND f.is_active=true
WHERE NOT EXISTS (SELECT 1 FROM public.boiler_fault_candidates c WHERE c.candidate_key=s.candidate_key);

DO $$
DECLARE v_actual bigint;
BEGIN
  SELECT count(*) INTO v_actual FROM public.boiler_fault_candidates c
  JOIN stage3_candidate_seed s ON s.candidate_key=c.candidate_key
  JOIN public.boiler_official_models m ON m.id=c.official_model_id
  JOIN public.boiler_model_families f ON f.id=c.family_id
  WHERE f.brand=s.brand AND m.official_model_name=s.official_model AND c.error_code=s.error_code
    AND c.verification_status='verified' AND c.is_active=true
    AND c.evidence_source_type=s.evidence_source_type AND c.evidence_url=s.evidence_url
    AND length(trim(c.evidence_note))>0;
  IF v_actual <> 192 THEN
    RAISE EXCEPTION 'Stage 3 stopped: lambert expected 192 verified candidates, found %', v_actual;
  END IF;
END $$;
COMMIT;
